version: 2.1

jobs:
  build-test:
    working_directory: ~/project
    docker:
      - image: circleci/openjdk:8-jdk-stretch-node-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

workflows:
  build-deploy:
    jobs:
      - build-test